'use client';

import React, { useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Sparkles, AlertCircle, RefreshCw, ChevronDown, Award, ArrowLeft } from 'lucide-react';
import apiClient from '@/lib/apiClient';
import { queryKeys } from '@/lib/queryKeys';
import { InterviewKitResult } from '@/types';
import { useAuthStore } from '@/stores/authStore';
import { toast } from '@/components/ui/Toaster';
import { cn } from '@/lib/utils';

export default function StandaloneInterviewKitPage() {
  const params = useParams();
  const router = useRouter();
  const queryClient = useQueryClient();
  const applicationId = params.id as string;
  
  const user = useAuthStore((s) => s.user);
  const [activeQuestionIdx, setActiveQuestionIdx] = useState<number | null>(null);

  // Fetch Interview Kit Query
  const {
    data: kit,
    isLoading,
    isError,
    error,
  } = useQuery<InterviewKitResult & { notReady?: boolean }>({
    queryKey: queryKeys.applications.kit(applicationId),
    queryFn: async () => {
      try {
        const response = await apiClient.get<InterviewKitResult>(
          `/api/applications/${applicationId}/interview-kit`
        );
        return response.data;
      } catch (err: any) {
        if (err.response?.status === 404) {
          return { notReady: true } as any;
        }
        throw err;
      }
    },
    refetchInterval: (query) => {
      const data = query.state.data as any;
      if (data && data.notReady) {
        return 5000;
      }
      return false;
    },
  });

  // Regenerate Kit Mutation
  const regenerateMutation = useMutation({
    mutationFn: async () => {
      const response = await apiClient.post(
        `/api/applications/${applicationId}/interview-kit/regenerate`
      );
      return response.data;
    },
    onSuccess: () => {
      toast('Regeneration Queued!', {
        description: 'AI is recreating the interview questions. Please wait...',
        type: 'success',
      });
      queryClient.setQueryData(queryKeys.applications.kit(applicationId), { notReady: true });
      queryClient.invalidateQueries({ queryKey: queryKeys.applications.kit(applicationId) });
    },
    onError: (err: any) => {
      toast('Regeneration Failed', {
        description: err.response?.data?.detail || 'An error occurred while queueing regeneration.',
        type: 'error',
      });
    },
  });

  const isHrAdmin = user?.role === 'HRAdmin';

  const handleRegenerate = () => {
    if (!isHrAdmin) {
      toast('Permission Denied', {
        description: 'Only HR Admins can regenerate interview kits.',
        type: 'error',
      });
      return;
    }
    regenerateMutation.mutate();
  };

  const isKitNotReady = kit && (kit as any).notReady;

  return (
    <div className="flex flex-col gap-6 w-full max-w-3xl mx-auto py-4 animate-in fade-in duration-300">
      
      {/* Header Navigation */}
      <div className="flex items-center gap-3">
        <button
          onClick={() => router.back()}
          className="p-2 border border-white/5 bg-white/5 rounded-xl hover:text-white transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
        </button>
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Interview Guide</h1>
          <p className="text-xs text-muted-foreground mt-0.5">
            AI-generated questions tailored to the candidate&apos;s fit profile.
          </p>
        </div>
      </div>

      {isLoading ? (
        <div className="flex flex-col items-center justify-center min-h-[300px] gap-3">
          <div className="w-8 h-8 border-3 border-violet-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-xs text-muted-foreground">Loading candidate interview questions...</p>
        </div>
      ) : isError ? (
        <div className="flex flex-col items-center justify-center p-8 border border-rose-500/20 bg-rose-500/5 rounded-2xl gap-2 text-center text-rose-400 min-h-[200px]">
          <AlertCircle className="w-8 h-8" />
          <p className="text-sm font-semibold">Failed to load interview kit</p>
          <p className="text-xs opacity-80 max-w-xs">{(error as any)?.message}</p>
        </div>
      ) : isKitNotReady ? (
        <div className="flex flex-col items-center justify-center p-8 border border-white/5 bg-white/5 rounded-2xl gap-3 text-center min-h-[250px]">
          <div className="w-6 h-6 border-2 border-violet-500 border-t-transparent rounded-full animate-spin" />
          <h4 className="font-semibold text-sm">AI Interview Kit Generating</h4>
          <p className="text-xs text-muted-foreground max-w-xs leading-relaxed">
            The kit is currently being generated by GPT-4o. This page will update automatically when the kit is ready.
          </p>
        </div>
      ) : kit ? (
        <div className="flex flex-col gap-6">
          
          {/* Profile overview card */}
          <div className="glass-panel p-6 rounded-2xl border border-white/5 flex items-start justify-between gap-4">
            <div className="min-w-0">
              <h4 className="font-bold text-lg text-foreground truncate">{kit.CandidateName}</h4>
              <p className="text-sm text-muted-foreground truncate">{kit.JobTitle}</p>
            </div>
            <div className="flex items-center gap-1.5 bg-violet-500/15 border border-violet-500/25 px-3 py-1.5 rounded-lg shrink-0">
              <Award className="w-4 h-4 text-violet-400" />
              <span className="text-sm font-bold text-violet-300">{Math.round(kit.FitScore)}% Match</span>
            </div>
          </div>

          {/* Accordion Questions */}
          <div className="space-y-3">
            <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">
              Targeted Interview Questions ({kit.Questions.length})
            </span>
            
            <div className="space-y-3">
              {kit.Questions.map((q, idx) => {
                const isActive = activeQuestionIdx === idx;
                return (
                  <div
                    key={idx}
                    className={cn(
                      "rounded-xl border border-white/5 transition-all overflow-hidden",
                      isActive ? "bg-white/5 border-violet-500/20" : "bg-white/[0.01] hover:bg-white/[0.02]"
                    )}
                  >
                    <button
                      type="button"
                      onClick={() => setActiveQuestionIdx(isActive ? null : idx)}
                      className="w-full flex items-center justify-between p-4 text-left gap-4"
                    >
                      <div className="flex flex-col gap-1.5 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="text-[10px] font-bold bg-violet-500/10 border border-violet-500/20 text-violet-400 px-2 py-0.5 rounded">
                            {q.Category}
                          </span>
                          <span className="text-[10px] font-bold bg-slate-500/10 border border-slate-500/20 text-slate-400 px-2 py-0.5 rounded">
                            {q.Difficulty}
                          </span>
                        </div>
                        <h5 className="font-semibold text-sm leading-snug text-foreground mt-0.5">
                          {q.Question}
                        </h5>
                      </div>
                      <ChevronDown
                        className={cn(
                          "w-4 h-4 text-muted-foreground transition-transform shrink-0",
                          isActive && "rotate-180"
                        )}
                      />
                    </button>

                    {isActive && (
                      <div className="px-4 pb-4 pt-1 border-t border-white/5 bg-black/10 flex flex-col gap-2 animate-in fade-in duration-200">
                        <span className="text-[10px] font-bold text-violet-400 uppercase tracking-wider">
                          What to Listen For (Rationale)
                        </span>
                        <p className="text-xs text-muted-foreground leading-relaxed">
                          {q.Rationale}
                        </p>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Standalone Action Footer */}
          <div className="glass-panel p-6 rounded-2xl border border-white/5 flex items-center justify-between gap-4 bg-black/20">
            <div className="text-xs text-muted-foreground max-w-sm">
              {isHrAdmin ? (
                'Trigger regeneration to query GPT-4o for a completely fresh set of assessment questions.'
              ) : (
                <span className="text-amber-400">Regeneration is restricted to HR Admin users only.</span>
              )}
            </div>

            <button
              onClick={handleRegenerate}
              disabled={regenerateMutation.isPending || !isHrAdmin}
              className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-bold bg-violet-600 hover:bg-violet-500 text-white disabled:opacity-40 transition-all shadow shadow-violet-600/15"
            >
              <RefreshCw className={cn("w-3.5 h-3.5", regenerateMutation.isPending && "animate-spin")} />
              Regenerate Interview Guide
            </button>
          </div>
        </div>
      ) : (
        <div className="text-center text-muted-foreground text-xs p-8">
          No interview kit data found.
        </div>
      )}
    </div>
  );
}
